{
 "title": "CSM Environments Install Progress Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total error count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "error_count" }
   ]
  },
  {
   "title": "Total unknown count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unknown_count" }
   ]
  },
  {
   "title": "Total Warning count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "warning_count" }
   ]
  },
  {
   "title": "Total failure count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "failure_count" }
   ]
  },
  {
   "title": "Total not responding count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "expr": "not_responding_count" }
   ]
  }
 ]
}