{
 "title": "USB Device errors",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "USB device setup address not responding count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "usb_device_not_responding_setup_address_count"
    }
   ]
  },
  {
   "title": "USB device disconnect error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "usb_device_disconnect_error_count"
    }
   ]
  },
  {
   "title": "USB device port1 error message",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "usb_device_port1_error" }
   ]
  },
  {
   "title": "Total USB device enumerate failure count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "enumerate_usb_device_error_count"
    }
   ]
  },
  {
   "title": "Total USB device descriptor read error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "usb_device_descriptor_read_error_count"
    }
   ]
  },
  {
   "title": "Total USB device address accept read error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "usb_device_address_accept_error_count"
    }
   ]
  }
 ]
}