{
 "title": "Boot DHCP errors",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "BMC reset for dhcp request count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bmc_reset_dhcp_request_notice_count"
    }
   ]
  },
  {
   "title": "dracut-initqueue dhcp for interface failed count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "dracut_initqueue_dhcp_interface_failed_warning_count"
    }
   ]
  },
  {
   "title": "dracut-initqueue dhcp for unsend packet count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "dracut_initqueue_dhcp_packet_unsend_count"
    }
   ]
  },
  {
   "title": "dracut-initqueue dhcp for discovery failed count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "dracut_initqueue_dhcp_discovery_failed_count"
    }
   ]
  },
  {
   "title": "dhcp server boot info failure count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "dhcp_server_boot_info_discovery_failure_count"
    }
   ]
  }
 ]
}