{
 "title": "Boot Monitoring - Frequency of message about known issues",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "BMC reset for dhcp request count",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bmc_reset_dhcp_request_notice_count"
    }
   ]
  },
  {
   "title": "Pool Allocation failed",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pool_allocation_failed_count" }
   ]
  },
  {
   "title": "dxe boot handler failed",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dxe_tpm_boot_handler_measure_failed_count"
    }
   ]
  },
  {
   "title": "Pcieport DPC error - Total Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "pcieport_dpc_error_containment_capabilities_error_count"
    }
   ]
  },
  {
   "title": "Cloud-init Authentication failure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cloud_init_authentication_failed_count"
    }
   ]
  },
  {
   "title": "Pcieport DPC error - Last Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pcieport_dpc_error_containment_capabilities_error_count"
    }
   ]
  },
  {
   "title": "Hub external port failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "hub_ext_port_status_failed_count"
    }
   ]
  }
 ]
}