{
 "title": "Boot PXE Errors",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total pxe server response timeout count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pxe_server_response_timeout_count"
    }
   ]
  },
  {
   "title": "Total pxe no offer received count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "pxe_no_offer_received_count" }
   ]
  },
  {
   "title": "Total pxe exit error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pxe_exit_error" }
   ]
  },
  {
   "title": "Total pxe remote boot cancelled count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pxe_remote_boot_cancelled_count"
    }
   ]
  },
  {
   "title": "Total pxe unexpected network error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pxe_unexpected_network_error_count"
    }
   ]
  }
 ]
}